# 文件路径: .github/workflows/build.yml
name: Build mc-status-api Binaries

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

  
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install --frozen-lockfile || yarn install

      - name: Install pkg globally
        run: yarn global add pkg

      - name: Build binaries
        run: |
          if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            npx pkg . --targets node18-linux-x64,node18-linux-arm64 --out-path dist
          elif [ "${{ matrix.os }}" == "macos-latest" ]; then
            npx pkg . --targets node18-macos-x64,node18-macos-arm64 --out-path dist
          elif [ "${{ matrix.os }}" == "windows-latest" ]; then
            npx pkg . --targets node18-win-x64,node18-win-arm64 --out-path dist
          fi

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: mc-status-api-${{ github.ref_name }}-${{ matrix.os }}
          path: dist/*
